// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComXyoTl3Cg4n-sEdcDMdU_IftIbA3I9E',
    appId: '1:896411670124:web:065fcc6303026e9fa7aa49',
    messagingSenderId: '896411670124',
    projectId: 'expanses-app-1488',
    authDomain: 'expanses-app-1488.firebaseapp.com',
    storageBucket: 'expanses-app-1488.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZczPCGV4_kr44I_80zXDuyz4FBhBC7BQ',
    appId: '1:896411670124:android:513567523e48662ca7aa49',
    messagingSenderId: '896411670124',
    projectId: 'expanses-app-1488',
    storageBucket: 'expanses-app-1488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0nzVcQkpMxp--bUvEi4Pt4Y5l9bKHXA',
    appId: '1:896411670124:ios:e0cdac26ab6be93ba7aa49',
    messagingSenderId: '896411670124',
    projectId: 'expanses-app-1488',
    storageBucket: 'expanses-app-1488.appspot.com',
    iosClientId: '896411670124-09e3trbl58s6ohqgqj1epmpbnuh9bv5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.expansesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj0nzVcQkpMxp--bUvEi4Pt4Y5l9bKHXA',
    appId: '1:896411670124:ios:e0cdac26ab6be93ba7aa49',
    messagingSenderId: '896411670124',
    projectId: 'expanses-app-1488',
    storageBucket: 'expanses-app-1488.appspot.com',
    iosClientId: '896411670124-09e3trbl58s6ohqgqj1epmpbnuh9bv5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.expansesApp',
  );
}
